sudo: required

services:
- docker

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev
    - rpm

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies
- gem install --no-document fpm

script:
- "./.travis-build.sh"

deploy:
- provider: script
  script: "./.travis-deploy.sh"
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray-deb.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray-rpm.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-monitor/bintray.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-monitor/bintray-deb.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-monitor/bintray-rpm.json
  on:
    branch: master
  skip_cleanup: true
