sudo: required

services:
- docker

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev
    - rpm

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies
- gem install --no-ri --no-rdoc fpm

env:
- FPM_PACKAGE_INFO="--license MIT --vendor CoinMetrics.io --url https://github.com/coinmetrics-io/haskell-tools"

script:
- mkdir bin pkg
- stack --no-terminal test --haddock --no-haddock-deps --copy-bins --local-bin-path bin
- fpm -s dir -t deb -n coinmetrics-export -p pkg $FPM_PACKAGE_INFO -d libpq5 -v 0.0.0.${TRAVIS_BUILD_NUMBER} bin/coinmetrics-export=/usr/bin/
- fpm -s dir -t rpm -n coinmetrics-export -p pkg $FPM_PACKAGE_INFO -d postgresql-libs -v 0.0.0.${TRAVIS_BUILD_NUMBER} bin/coinmetrics-export=/usr/bin/
- envsubst < coinmetrics-export/bintray.json.in > coinmetrics-export/bintray.json
- envsubst < coinmetrics-export/bintray-deb.json.in > coinmetrics-export/bintray-deb.json
- envsubst < coinmetrics-export/bintray-rpm.json.in > coinmetrics-export/bintray-rpm.json
- cp Dockerfile bin/ && docker build -t ${DOCKER_REPO}:latest bin
- docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}
- docker push ${DOCKER_REPO}:latest

deploy:
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray-deb.json
  on:
    branch: master
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray-rpm.json
  on:
    branch: master
  skip_cleanup: true
