sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev
    - rpm

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies
- gem install --no-ri --no-rdoc fpm

script:
- mkdir bin
- stack --no-terminal test --haddock --no-haddock-deps --copy-bins --local-bin-path bin
- fpm -s dir -t deb -n coinmetrics-export -v 0.0.0.${TRAVIS_BUILD_NUMBER} bin/coinmetrics-export=/usr/bin/
- fpm -s dir -t rpm -n coinmetrics-export -v 0.0.0.${TRAVIS_BUILD_NUMBER} bin/coinmetrics-export=/usr/bin/

before_deploy:
- envsubst < coinmetrics-export/bintray.json.in > coinmetrics-export/bintray.json
- envsubst < coinmetrics-export/bintray-deb.json.in > coinmetrics-export/bintray-deb.json
- envsubst < coinmetrics-export/bintray-rpm.json.in > coinmetrics-export/bintray-rpm.json

deploy:
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray.json
  on:
    branch: deploy # temporary
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray-deb.json
  on:
    branch: deploy # temporary
  skip_cleanup: true
- provider: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  file: coinmetrics-export/bintray-rpm.json
  on:
    branch: deploy # temporary
  skip_cleanup: true
