resolver: lts-10.0

packages:
- coinmetrics
- coinmetrics-cardano
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar

extra-deps:
#- avro-0.2.0.0
- git: https://github.com/LeifW/avro.git
  commit: bf1dcd3d663022afa4aa6bcecd2752cb807cb06e
- pure-zlib-0.6
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: d5d912cddf9d78abc73b0649681409d987a7b83b
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres

ghc-options:
  "$locals": -threaded -Wall -Wno-tabs
