resolver: lts-10.0

packages:
- coinmetrics
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota

extra-deps:
#- avro-0.2.0.0
- git: https://github.com/LeifW/avro.git
  commit: bf1dcd3d663022afa4aa6bcecd2752cb807cb06e
- pure-zlib-0.6
- diskhash-0.0.4.0

ghc-options:
  "$locals": -threaded -Wall -Wno-tabs
