resolver: lts-11.10

packages:
- coinmetrics
- coinmetrics-cardano
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar

extra-deps:
- avro-0.3.0.4
- pure-zlib-0.6.3
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: 046cd816becc1529660efc899d82182a6647024a
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres

ghc-options:
  "$locals": -threaded -Wall -Wno-tabs
