resolver: lts-10.0

packages:
- coinmetrics
- coinmetrics-cardano
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota
- coinmetrics-ripple
- coinmetrics-stellar

extra-deps:
#- avro-0.2.0.0
- git: https://github.com/LeifW/avro.git
  commit: bf1dcd3d663022afa4aa6bcecd2752cb807cb06e
- pure-zlib-0.6
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: cbefafd1ceb7abe9d29525b5285fc45e66baa97a
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres

ghc-options:
  "$locals": -threaded -Wall -Wno-tabs
