resolver: lts-12.0

packages:
- coinmetrics
- coinmetrics-all-blockchains
- coinmetrics-bitcoin
- coinmetrics-cardano
- coinmetrics-eos
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar
- coinmetrics-waves

extra-deps:
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: 14f88a6cacb35cbf6954adaa3e47d936d8f37d91
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres
