resolver: lts-12.0

packages:
- coinmetrics
- coinmetrics-all-blockchains
- coinmetrics-bitcoin
- coinmetrics-cardano
- coinmetrics-eos
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar
- coinmetrics-waves

extra-deps:
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: 2474e93a113727553a18a5bbe7cada40d7e3c69b
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres

ghc-options:
  "$locals": -threaded -Wall -Wno-tabs
